### ISSUE TITLE
網域編輯問題 #1 Domain Issue #1 【已完成】

### ISSUE THREAD

**Issue by miniblack0662** [Hamster67/Hamster671#2]
加了 "mc." hamval.cloudns.be 
這個 ^^^^^^ 子網域只是讓你要打的字越來越多, 倒不如不要加
還有 網站的 www. 其實也是不必要的
正常會 www.YourDomain.com
既然是子網域
也沒有加 www. 的意義了

**Comment by Hamster67-NOT-USE-NOW** [comment]
已更改 hamval.cloudns.be 和 mc.hamval.cloudns.be 都可以加入
